import React from "react";
import { Link } from "react-router-dom";
import {
  ArrowRight,
  BookOpen,
  Target,
  TrendingUp,
  Users,
  Star,
  CheckCircle,
  Brain,
  Award,
  Clock,
} from "lucide-react";

const LandingPage: React.FC = () => {
  const features = [
    {
      icon: Brain,
      title: "AI-Powered Learning",
      description:
        "Personalized roadmaps generated by advanced AI to match your goals and learning style.",
    },
    {
      icon: Target,
      title: "Goal-Oriented Approach",
      description:
        "Set your learning objectives and get a structured path to achieve them efficiently.",
    },
    {
      icon: TrendingUp,
      title: "Progress Tracking",
      description:
        "Monitor your advancement with detailed analytics and performance insights.",
    },
    {
      icon: Award,
      title: "Interactive Assessments",
      description:
        "Test your knowledge with engaging quizzes and receive instant feedback.",
    },
  ];

  const testimonials = [
    {
      name: "Sarah Chen",
      role: "Frontend Developer",
      content:
        "PathWise transformed my learning journey. The AI-generated roadmap was exactly what I needed to transition into tech.",
      rating: 5,
    },
    {
      name: "Marcus Rodriguez",
      role: "Product Manager",
      content:
        "The personalized approach and progress tracking kept me motivated throughout my entire learning experience.",
      rating: 5,
    },
    {
      name: "Emily Johnson",
      role: "UX Designer",
      content:
        "Finally, a learning platform that adapts to my schedule and learning preferences. Absolutely game-changing.",
      rating: 5,
    },
  ];

  const stats = [
    { number: "10K+", label: "Active Learners" },
    { number: "500+", label: "Learning Paths" },
    { number: "95%", label: "Success Rate" },
    { number: "24/7", label: "AI Support" },
  ];

  return (
    <div className="min-h-screen bg-white dark:bg-dark-bg transition-colors duration-200">
      {/* Navigation */}
      <nav className="bg-white/95 dark:bg-dark-card/95 backdrop-blur-sm border-b border-light-border dark:border-dark-border sticky top-0 z-50 transition-colors duration-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-2">
              <img
                src="https://github.com/DarshanVarade/Data/blob/main/PathWise-s-logo.png?raw=true"
                alt="PathWise Logo"
                className="w-8 h-8"
              />
              <span className="text-xl font-bold text-light-text-primary dark:text-dark-text-primary">
                PathWise
              </span>
            </div>

            <div className="hidden md:flex items-center space-x-8">
              <a
                href="#features"
                className="text-light-text-secondary dark:text-dark-text-secondary hover:text-light-text-primary dark:hover:text-dark-text-primary transition-colors">
                Features
              </a>
              <a
                href="#how-it-works"
                className="text-light-text-secondary dark:text-dark-text-secondary hover:text-light-text-primary dark:hover:text-dark-text-primary transition-colors">
                How it Works
              </a>
              <a
                href="#testimonials"
                className="text-light-text-secondary dark:text-dark-text-secondary hover:text-light-text-primary dark:hover:text-dark-text-primary transition-colors">
                Testimonials
              </a>
            </div>

            <div className="flex items-center space-x-4">
              <Link
                to="/auth"
                className="text-light-text-secondary dark:text-dark-text-secondary hover:text-light-text-primary dark:hover:text-dark-text-primary font-medium transition-colors">
                Sign In
              </Link>
              <Link
                to="/auth"
                className="bg-gradient-to-r from-light-primary to-light-accent dark:from-dark-primary dark:to-dark-accent text-white px-6 py-2 rounded-lg font-medium hover:opacity-90 transition-all duration-200 transform hover:scale-105">
                Get Started
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-light-bg via-white to-light-primary/5 dark:from-dark-bg dark:via-dark-card dark:to-dark-primary/5 py-20 lg:py-32 transition-colors duration-200">
        <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold text-light-text-primary dark:text-dark-text-primary mb-6 leading-tight">
              Your Personal
              <span className="bg-gradient-to-r from-light-primary to-light-accent dark:from-dark-primary dark:to-dark-accent bg-clip-text text-transparent">
                {" "}
                Learning
              </span>
              <br />
              Journey Starts Here
            </h1>

            <p className="text-xl md:text-2xl text-light-text-secondary dark:text-dark-text-secondary mb-10 max-w-3xl mx-auto leading-relaxed">
              Transform your skills with AI-generated learning roadmaps tailored
              to your goals, pace, and learning style. Master any subject with
              personalized guidance.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6">
              <Link
                to="/auth"
                className="group bg-gradient-to-r from-light-primary to-light-accent dark:from-dark-primary dark:to-dark-accent text-white px-8 py-4 rounded-xl font-semibold text-lg hover:opacity-90 transition-all duration-200 transform hover:scale-105 flex items-center space-x-2 shadow-lg hover:shadow-xl">
                <span>Start Learning Today</span>
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-white dark:bg-dark-card border-b border-light-border dark:border-dark-border transition-colors duration-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="text-3xl md:text-4xl font-bold text-light-text-primary dark:text-dark-text-primary mb-2">
                  {stat.number}
                </div>
                <div className="text-light-text-secondary dark:text-dark-text-secondary font-medium">
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section
        id="features"
        className="py-20 bg-light-bg dark:bg-dark-bg transition-colors duration-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-light-text-primary dark:text-dark-text-primary mb-4">
              Why Choose PathWise?
            </h2>
            <p className="text-xl text-light-text-secondary dark:text-dark-text-secondary max-w-2xl mx-auto">
              Experience the future of personalized learning with cutting-edge
              AI technology
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <div
                  key={index}
                  className="bg-white dark:bg-dark-card rounded-2xl p-8 shadow-sm hover:shadow-lg transition-all duration-300 transform hover:-translate-y-1 border border-light-border dark:border-dark-border">
                  <div className="w-12 h-12 bg-gradient-to-br from-light-primary/10 to-light-accent/10 dark:from-dark-primary/10 dark:to-dark-accent/10 rounded-xl flex items-center justify-center mb-6">
                    <Icon className="w-6 h-6 text-light-primary dark:text-dark-primary" />
                  </div>
                  <h3 className="text-xl font-semibold text-light-text-primary dark:text-dark-text-primary mb-3">
                    {feature.title}
                  </h3>
                  <p className="text-light-text-secondary dark:text-dark-text-secondary leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section
        id="how-it-works"
        className="py-20 bg-white dark:bg-dark-card transition-colors duration-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-light-text-primary dark:text-dark-text-primary mb-4">
              How PathWise Works
            </h2>
            <p className="text-xl text-light-text-secondary dark:text-dark-text-secondary max-w-2xl mx-auto">
              Get started in minutes with our simple, AI-powered process
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-gradient-to-br from-light-primary to-light-accent dark:from-dark-primary dark:to-dark-accent rounded-full flex items-center justify-center mx-auto mb-6">
                <Target className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-light-text-primary dark:text-dark-text-primary mb-3">
                1. Set Your Goal
              </h3>
              <p className="text-light-text-secondary dark:text-dark-text-secondary">
                Tell us what you want to learn and our AI will understand your
                objectives
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 bg-gradient-to-br from-light-primary to-light-accent dark:from-dark-primary dark:to-dark-accent rounded-full flex items-center justify-center mx-auto mb-6">
                <BookOpen className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-light-text-primary dark:text-dark-text-primary mb-3">
                2. Get Your Roadmap
              </h3>
              <p className="text-light-text-secondary dark:text-dark-text-secondary">
                Receive a personalized learning path with structured lessons and
                milestones
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 bg-gradient-to-br from-light-primary to-light-accent dark:from-dark-primary dark:to-dark-accent rounded-full flex items-center justify-center mx-auto mb-6">
                <TrendingUp className="w-8 h-8 text-white" />
              </div>
              <h3 className="text-xl font-semibold text-light-text-primary dark:text-dark-text-primary mb-3">
                3. Track Progress
              </h3>
              <p className="text-light-text-secondary dark:text-dark-text-secondary">
                Monitor your advancement and celebrate achievements along the
                way
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section
        id="testimonials"
        className="py-20 bg-light-bg dark:bg-dark-bg transition-colors duration-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-light-text-primary dark:text-dark-text-primary mb-4">
              Loved by Learners Worldwide
            </h2>
            <p className="text-xl text-light-text-secondary dark:text-dark-text-secondary max-w-2xl mx-auto">
              Join thousands of successful learners who transformed their
              careers with PathWise
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div
                key={index}
                className="bg-white dark:bg-dark-card rounded-2xl p-8 shadow-sm border border-light-border dark:border-dark-border">
                <div className="flex items-center space-x-1 mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star
                      key={i}
                      className="w-5 h-5 text-yellow-400 fill-current"
                    />
                  ))}
                </div>
                <p className="text-light-text-primary dark:text-dark-text-primary mb-6 leading-relaxed">
                  "{testimonial.content}"
                </p>
                <div>
                  <div className="font-semibold text-light-text-primary dark:text-dark-text-primary">
                    {testimonial.name}
                  </div>
                  <div className="text-light-text-secondary dark:text-dark-text-secondary text-sm">
                    {testimonial.role}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-br from-light-primary to-light-accent dark:from-dark-primary dark:to-dark-accent">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-xl text-blue-100 mb-10 max-w-2xl mx-auto">
            Join thousands of learners who are already achieving their goals
            with PathWise. Start your personalized learning journey today.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6">
            <Link
              to="/auth"
              className="bg-white text-light-primary dark:text-dark-primary px-8 py-4 rounded-xl font-semibold text-lg hover:bg-gray-50 transition-all duration-200 transform hover:scale-105 flex items-center space-x-2 shadow-lg">
              <span>Get Started Free</span>
              <ArrowRight className="w-5 h-5" />
            </Link>

            <div className="flex items-center space-x-2 text-blue-100">
              <CheckCircle className="w-5 h-5" />
              <span>No credit card required</span>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-light-text-primary dark:bg-dark-bg text-white dark:text-dark-text-primary py-12 transition-colors duration-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="col-span-1 md:col-span-2">
              <Link
                to="/"
                className="flex items-center space-x-2 mb-4 hover:opacity-80 transition-opacity">
                <img
                  src="https://github.com/DarshanVarade/Data/blob/main/PathWise-s-logo.png?raw=true"
                  alt="PathWise Logo"
                  className="w-8 h-8"
                />
                <span className="text-xl font-bold">PathWise</span>
              </Link>
              <p className="text-gray-400 dark:text-dark-text-secondary max-w-md">
                Empowering learners worldwide with AI-driven personalized
                education. Transform your skills and achieve your goals with
                PathWise.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Product</h3>
              <ul className="space-y-2 text-gray-400 dark:text-dark-text-secondary">
                <li>
                  <a
                    href="#features"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    Features
                  </a>
                </li>
                <li>
                  <a
                    href="#how-it-works"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    How it Works
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    Pricing
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    API
                  </a>
                </li>
              </ul>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Company</h3>
              <ul className="space-y-2 text-gray-400 dark:text-dark-text-secondary">
                <li>
                  <a
                    href="#"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    About
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    Blog
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    Careers
                  </a>
                </li>
                <li>
                  <a
                    href="#"
                    className="hover:text-white dark:hover:text-dark-text-primary transition-colors">
                    Contact
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div className="border-t border-gray-800 dark:border-dark-border mt-12 pt-8 flex flex-col md:flex-row justify-between items-center">
            <p className="text-gray-400 dark:text-dark-text-secondary text-sm">
              © 2025 PathWise. All rights reserved.
            </p>
            <div className="flex items-center space-x-6 mt-4 md:mt-0">
              <a
                href="#"
                className="text-gray-400 dark:text-dark-text-secondary hover:text-white dark:hover:text-dark-text-primary transition-colors text-sm">
                Privacy Policy
              </a>
              <a
                href="#"
                className="text-gray-400 dark:text-dark-text-secondary hover:text-white dark:hover:text-dark-text-primary transition-colors text-sm">
                Terms of Service
              </a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
